# Generated by Django 6.1.1 on 2026-09-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('college', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=50)),
                ('roll_no', models.CharField(max_length=50)),
                ('tenth_percentage', models.FloatField()),
                ('twelfth_percentage', models.FloatField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('skills', models.CharField(blank=True, max_length=300)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
            ],
        ),
    ]
